Repopulate cookie when onboarding is called with accounts in the DB
nimiq/hub pull request #473
Opened 2022-01-08 15:09 UTC by sisou

On iOS, especially when the Wallet is installed to homescreen, the Hub sometimes deletes its cookie, even before 7 days are over (it should not delete any data in a PWA context, but maybe because the Hub is a non-first-party domain to the PWA and opens in a webview, it is still affected?). The IndexedDB & local storage in the webview is still present then.

This deletion of the Hub cookie leads to the Wallet triggering the onboarding flow as a redirect (`disableBack: true`). This PR uses this and short-circuits the onboarding request by simply responding with a full list of accounts, which also sets the cookie (through the `_reply()` function in the `RpcApi`).

2022-01-10 11:19 UTC, danimoh requested changes

2022-01-10 11:32 UTC, sisou commented on src/views/OnboardingSelector.vue
> +        if (this.request.disableBack && (BrowserDetection.isIOS() || BrowserDetection.isSafari())) {
The onboarding request is not in the `3rdPartyRequestWhitelist`, so no 3rd-party pages can call this request in the first place, it is stopped in the RpcApi already.

2022-01-10 11:34 UTC, sisou commented on src/views/OnboardingSelector.vue
> +                            const walletInfo = await WalletStore.Instance.get(entry.id);
Nice, that's better! :+1:

2022-01-10 11:41 UTC, sisou commented on src/views/OnboardingSelector.vue
> +        // cookie in the process.
Thanks, I used the PR description (with minimal wording changes).

2022-01-11 11:40 UTC, danimoh approved these changes

2022-01-11 11:45 UTC, merged