Change API to use a number array instead of a Uint8Array
nimiq/hub pull request #550
Opened 2024-11-13 17:46 UTC by blouflashdb

```
const clientObj: Uint8Array = new Uint8Array([21, 31]);
const message = JSON.stringify(clientObj)
console.log("clientObj", clientObj instanceof Uint8Array) 

const serverObj: Uint8Array = JSON.parse(message);
console.log("serverObj", serverObj instanceof Uint8Array) // returns false because Uint8Array is serialized as an object
```

With this change SignedMessage can be serialized and deserialized without problems. Its a breaking API change tho

2024-11-13 22:55 UTC, sisou commented
Just like you are doing `Array.from()` now internally, can't you just do that in your code?

```js
JSON.parse(Array.from(message));
```

Uint8Array cannot be JSON serialized without helpers.

2024-11-17 21:14 UTC, danimoh commented
Hi @blouflashdb,
thanks for your considerations and the pull request. I see where you're coming from, but personally I think that `Uint8Array` is in fact more intuitive and consistent. `Uint8Array` makes it very clear that bytes are being returned here, `number[]` could also include `NaN`, negative, fractional or infinite values or values which don't fit a single byte, i.e. the documentation would need to clearly state what kind of values are to be expected, or users of the API strictly speaking would need to check for unsupported values, which ends up being more code even than simply converting the `Uint8Array` to `number[]` as a user. Also, `number[]` is not used anywhere else in the API and keeping `Uint8Array` would therefore be more consistent. I think converting it yourself as a user, as you're currently doing it, is the way to go.

I would favor keeping it a `Uint8Array`.

2024-11-17 21:19 UTC, danimoh requested changes
If we were to make this change, some the expected values should be documented, but I think we should keep it being `Uint8Array`s.

2024-11-17 21:19 UTC, danimoh commented on docs/api-methods/30_sign-message.md
> +    signature: number[];        // Signature for the message
Should state which values are to be expected here, i.e. integers in the range 0..255.

2024-11-17 21:19 UTC, danimoh commented on client/PublicRequestTypes.ts
> +    signature: number[];
Should state which values are to be expected here, i.e. integers in the range 0..255.

2024-11-17 21:23 UTC, closed without merging